name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: pyinstaller main.py --windowed --onefile --name map-tiler

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: dist/map-tiler.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: app
        path: .

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: map-tiler.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
